export const myPosts = [
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "<bold>Lorem</bold> ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://post.healthline.com/wp-content/uploads/2020/08/3180-Pug_green_grass-732x549-thumbnail-732x549.jpg",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://post.healthline.com/wp-content/uploads/2020/08/3180-Pug_green_grass-732x549-thumbnail-732x549.jpg",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
  {
    title: "Hello World!",
    category: "JavaScript Days",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
];

export const whyPosts = [
  {
    title: "Why Blog?",
    date: "July 14th, 2022",
    img: "https://miro.medium.com/max/1400/1*_zx26GIKgxbrv0DcXl48gA.png",
    entry:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat expedita eligendi, reprehenderit tenetur inventore vitae? Excepturi architecto nemo voluptates magni qui sapiente pariatur porro consequuntur! Repellendus, temporibus possimus id et nobis impedit facilis ipsa, eligendi dolorem perspiciatis similique eius reprehenderit necessitatibus, repudiandae quisquam expedita exercitationem quaerat iusto placeat deleniti voluptates? Inventore sit quaerat provident est, reiciendis officia culpa aspernatur tempore corporis, voluptatibus vel nisi dolorem debitis libero fuga ex laborum impedit nam harum delectus, et sed fugiat expedita corrupti! Assumenda enim illum quas a quo! Atque, dolorum. Iste voluptatibus provident ad blanditiis. Commodi, vitae. Omnis numquam animi nulla minima doloremque.",
  },
];
